Repository CMPUT301F22T12/CMPUT301Project, pull requests merged in 2022-11, with the labels that each got.

#52 Refactor Shopping List Code & UI
  android/301Project/.idea/misc.xml
  android/301Project/app/src/main/AndroidManifest.xml
  android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListActivity.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
  android/301Project/app/src/main/java/com/example/a301project/application/MyApplication.java
  android/301Project/app/src/main/java/com/example/a301project/base/BaseAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/shopping/adapter/ShoppingListAdapter.kt
  android/301Project/app/src/main/java/com/example/a301project/shopping/entity/ShoppingItem.java
  android/301Project/app/src/main/java/com/example/a301project/util/SortUtil.kt
  android/301Project/app/src/main/java/com/example/a301project/util/ToastUtil.java
  android/301Project/app/src/main/res/drawable/btn_bg.xml
  android/301Project/app/src/main/res/drawable/btn_blue_bg.xml
  android/301Project/app/src/main/res/drawable/btn_orange_bg.xml
  android/301Project/app/src/main/res/layout/activity_shopping_list.xml
  android/301Project/app/src/main/res/layout/add_food_dialog.xml
  android/301Project/app/src/main/res/layout/shopping_add_item_dialog.xml
  android/301Project/app/src/main/res/layout/shopping_item.xml
  android/301Project/app/src/main/res/layout/shopping_row_layout.xml
  android/301Project/app/src/main/res/layout/success_dialog.xml
Labels: enhancement

#56 Redid ingredient edit menu and added appropriate selectors
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/Ingredient.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
  android/301Project/app/src/main/res/layout/add_edit_ingredientlayout.xml
  android/301Project/app/src/main/res/layout/ingredient_unit_item.xml
  android/301Project/app/src/main/res/values/dimens.xml
  android/301Project/app/src/main/res/values/strings.xml
Labels: enhancement

#58 Added ingredient delete button
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
  android/301Project/app/src/main/res/layout/add_edit_ingredientlayout.xml
Labels: enhancement

#61 Fixed Firestore conversion bug for the shopping list
  android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
Labels: bug

#63 Refactor Firebase Controller Getters
  android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
Labels: enhancement

#71 Add Upload Image and Fix Back Button Bug
  android/301Project/.idea/misc.xml
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlanActivity.java
  android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeActivity.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListActivity.java
  android/301Project/app/src/main/res/layout/activity_recipe.xml
  android/301Project/app/src/main/res/layout/add_edit_recipe_layout.xml
Labels: bug

#74 loads of javadoc
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/CustomList.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlan.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlanActivity.java
  android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
  android/301Project/app/src/main/java/com/example/a301project/Recipe.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeListAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListActivity.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
Labels: documentation

#77 Add JavaDoc for MealPlanActivity and MealPlanListAdapter
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlanActivity.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlanListAdapter.java
Labels: documentation

#76 Fix Null Image Bug
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
Labels: bug

#81 Add Ingredient Unit Test!!!
  android/301Project/app/build.gradle
  android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
  android/301Project/app/src/test/java/com/example/a301project/ExampleUnitTest.java
  android/301Project/app/src/test/java/com/example/a301project/IngredientControllerTest.java
Labels: test

#85 Refactor All Activities to Fragments
  android/301Project/.idea/.gitignore
  android/301Project/app/src/androidTest/java/com/example/a301project/IngredientFragmentTest.java
  android/301Project/app/src/androidTest/java/com/example/a301project/NavActivityTest.java
  android/301Project/app/src/main/AndroidManifest.xml
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/CustomList.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlan.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlanFragment.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlanListAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListFragment.java
  android/301Project/app/src/main/res/layout/activity_meal_plan.xml
  android/301Project/app/src/main/res/layout/activity_shopping_list.xml
  android/301Project/app/src/test/java/com/example/a301project/IngredientControllerTest.java
Labels: enhancement

#87 Add Ingredients to Recipes
  android/301Project/.idea/misc.xml
  android/301Project/app/src/main/AndroidManifest.xml
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/Ingredient.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
  android/301Project/app/src/main/java/com/example/a301project/IngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeIngredientListAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListFragment.java
  android/301Project/app/src/main/res/drawable-hdpi/delete.xml
  android/301Project/app/src/main/res/drawable/delete_rounded.xml
  android/301Project/app/src/main/res/layout/activity_ingredient.xml
  android/301Project/app/src/main/res/layout/activity_meal_plan.xml
  android/301Project/app/src/main/res/layout/activity_recipe.xml
  android/301Project/app/src/main/res/layout/activity_shopping_list.xml
  android/301Project/app/src/main/res/layout/add_edit_recipe_layout.xml
  android/301Project/app/src/main/res/layout/add_ingredient_row_layout.xml
  android/301Project/app/src/main/res/menu/nav_items.xml
  android/301Project/app/src/main/res/values-night/themes.xml
  android/301Project/app/src/main/res/values/themes.xml
  android/301Project/app/src/test/java/com/example/a301project/IngredientControllerTest.java
Labels: enhancement

#88 Update Ingredient Dropdown Delay
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
Labels: bug

#91 Can pull ingredient spinner values from Firebase and add new ones
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientController.java
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeController.java
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/res/layout/activity_ingredient.xml
  android/301Project/app/src/main/res/layout/activity_recipe.xml
  android/301Project/app/src/main/res/layout/add_edit_recipe_layout.xml
Labels: enhancement

#94 Fix ImageView Bug
  android/301Project/app/src/main/java/com/example/a301project/RecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/RecipeListAdapter.java
Labels: bug

#103 Auto Login as Admin with Flag
  android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
Labels: enhancement

#127 ShoppingList changes
  android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
  android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
  android/301Project/app/src/main/java/com/example/a301project/Ingredient.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListFragment.java
  android/301Project/app/src/main/res/layout/activity_shopping_list.xml
Labels: enhancement

#128 UMLDiagramPart4
  img/CMPUT301_UMLDiagramPart4.pdf
  img/CMPUT301_UMLDiagramPart4.svg
Labels: documentation

#133 ShoppingList
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListAdapter.java
  android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
  android/301Project/app/src/main/res/layout/shopping_row_layout.xml
Labels: enhancement

#138 Added filter to meal plan so that startDate <= endDate
  android/301Project/app/src/main/java/com/example/a301project/AddEditMealPlanFragment.java
  android/301Project/app/src/main/java/com/example/a301project/MealPlan.java
Labels: enhancement

#139 Added ShoppingList and MealPlan Intent tests
  android/301Project/.idea/androidTestResultsUserPreferences.xml
  android/301Project/app/src/androidTest/java/com/example/a301project/IngredientFragmentTest.java
  android/301Project/app/src/androidTest/java/com/example/a301project/MealPlanFragmentTest.java
  android/301Project/app/src/androidTest/java/com/example/a301project/ShoppingListFragmentTest.java
Labels: test
